import type { Metadata } from 'next'
import AppDetailTemplate from '@/components/AppDetailTemplate'

export const metadata: Metadata = {
  title: 'StarLegalAI - AI-Powered Contract Review',
  description: 'StarLegalAI is an AI-powered SaaS platform for contract analysis, giving attorneys and businesses clause-level risk and obligation insights.',
  keywords: 'StarLegalAI, AI contract review, legal tech, contract analysis SaaS',
}

export default function Page() {
  return (
    <AppDetailTemplate
      name="StarLegalAI"
      tagline="AI-powered contract review with clause-level risk and obligation insights."
      category="Legal"
      status="Live"
      description="StarLegalAI is an AI-powered SaaS platform purpose-built for contract analysis. Attorneys, businesses, startups, and individuals upload legal documents and receive structured, clause-level insights — risks, obligations, deadlines, key terms, and plain-language summaries — generated by the Claude API."
      highlights={[
        'Clause-level risk, obligation, and deadline extraction',
        'Plain-language summaries of complex legal documents',
        'Free one-document trial with a subscription model beyond that',
      ]}
      externalUrl="https://starlegalai.com"
    />
  )
}
